
/datum/sprite_accessory/hair
	species_allowed = list(SPECIES_HUMAN, SPECIES_UNATHI, SPECIES_VOX, SPECIES_AKULA, SPECIES_VULP, SPECIES_VASS, SPECIES_TAJ, SPECIES_IPC, SPECIES_CUSTOM, SPECIES_OLDUNATHI)

/datum/sprite_accessory/facial_hair
	species_allowed = list(SPECIES_HUMAN, SPECIES_UNATHI, SPECIES_VOX, SPECIES_AKULA, SPECIES_VULP, SPECIES_VASS, SPECIES_TAJ, SPECIES_IPC, SPECIES_CUSTOM, SPECIES_OLDUNATHI)